version: "3"

services:
  dev:
    command: yarn serve
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    volumes:
      - .:/frontapp
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - VUE_APP_HOST_URL=http://0.0.0.0:8000
